name: DART
channels:
  - pytorch3d
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - alsa-lib=1.2.11=hd590300_1
  - aom=3.8.1=h59595ed_0
  - attr=2.5.1=h166bdaf_1
  - blas=1.0=mkl
  - brotli-python=1.1.0=py38h17151c0_1
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2024.2.2=hbcca054_0
  - cairo=1.18.0=h3faef2a_0
  - certifi=2024.2.2=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cuda-cudart=11.8.89=0
  - cuda-cupti=11.8.87=0
  - cuda-libraries=11.8.0=0
  - cuda-nvrtc=11.8.89=0
  - cuda-nvtx=11.8.86=0
  - cuda-runtime=11.8.0=0
  - cycler=0.12.1=pyhd8ed1ab_0
  - dataclasses=0.8=pyhc8e2a94_3
  - dav1d=1.2.1=hd590300_0
  - dbus=1.13.6=h5008d03_3
  - expat=2.6.1=h59595ed_0
  - ffmpeg=6.1.1=gpl_h8007c5b_104
  - filelock=3.13.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=h267a509_2
  - fribidi=1.0.10=h36c2ea0_0
  - fvcore=0.1.5.post20221221=pyhd8ed1ab_0
  - gettext=0.21.1=h27087fc_0
  - glib=2.78.4=hfc55251_4
  - glib-tools=2.78.4=hfc55251_4
  - gmp=6.3.0=h59595ed_0
  - gmpy2=2.1.2=py38h793c122_1
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.13=h58526e2_1001
  - gst-plugins-base=1.22.9=h8e1006c_0
  - gstreamer=1.22.9=h98fc4e7_0
  - harfbuzz=8.3.0=h3d44ed6_0
  - icu=73.2=h59595ed_0
  - idna=3.6=pyhd8ed1ab_0
  - intel-openmp=2022.1.0=h9e868ea_3769
  - iopath=0.1.9=pyhd8ed1ab_0
  - jinja2=3.1.3=pyhd8ed1ab_0
  - joblib=1.3.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py38h7f3f72f_1
  - krb5=1.21.2=h659d440_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.1=cxx17_h59595ed_2
  - libass=0.17.1=h8fe9dca_1
  - libblas=3.9.0=16_linux64_mkl
  - libcap=2.69=h0f662aa_0
  - libcblas=3.9.0=16_linux64_mkl
  - libclang=15.0.7=default_hb11cfb5_4
  - libclang13=15.0.7=default_ha2b6cf4_4
  - libcublas=11.11.3.6=0
  - libcufft=10.9.0.58=0
  - libcufile=1.9.0.20=0
  - libcups=2.3.3=h4637d8d_4
  - libcurand=10.3.5.119=0
  - libcusolver=11.4.1.48=0
  - libcusparse=11.7.5.86=0
  - libdeflate=1.19=hd590300_0
  - libdrm=2.4.120=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.6.1=h59595ed_0
  - libffi=3.4.2=h7f98852_5
  - libflac=1.4.3=h59595ed_0
  - libgcc-ng=13.2.0=h807b86a_5
  - libgcrypt=1.10.3=hd590300_0
  - libgfortran-ng=13.2.0=h69a702a_5
  - libgfortran5=13.2.0=ha4646dd_5
  - libglib=2.78.4=hf2295e7_4
  - libgomp=13.2.0=h807b86a_5
  - libgpg-error=1.48=h71f35ed_0
  - libhwloc=2.9.3=default_h554bfaf_1009
  - libiconv=1.17=hd590300_2
  - libidn2=2.3.7=hd590300_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=16_linux64_mkl
  - libllvm15=15.0.7=hb3ce162_4
  - libnpp=11.8.0.86=0
  - libnsl=2.0.1=hd590300_0
  - libnvjpeg=11.9.0.86=0
  - libogg=1.3.4=h7f98852_1
  - libopenvino=2023.3.0=h2e90f83_2
  - libopenvino-auto-batch-plugin=2023.3.0=hd5fc58b_2
  - libopenvino-auto-plugin=2023.3.0=hd5fc58b_2
  - libopenvino-hetero-plugin=2023.3.0=h3ecfda7_2
  - libopenvino-intel-cpu-plugin=2023.3.0=h2e90f83_2
  - libopenvino-intel-gpu-plugin=2023.3.0=h2e90f83_2
  - libopenvino-ir-frontend=2023.3.0=h3ecfda7_2
  - libopenvino-onnx-frontend=2023.3.0=h469e5c9_2
  - libopenvino-paddle-frontend=2023.3.0=h469e5c9_2
  - libopenvino-pytorch-frontend=2023.3.0=h59595ed_2
  - libopenvino-tensorflow-frontend=2023.3.0=he1e0747_2
  - libopenvino-tensorflow-lite-frontend=2023.3.0=h59595ed_2
  - libopus=1.3.1=h7f98852_1
  - libpciaccess=0.18=hd590300_0
  - libpng=1.6.43=h2797004_0
  - libpq=16.2=h33b98f1_0
  - libprotobuf=4.25.2=h08a7969_1
  - libsndfile=1.2.2=hc60ed4a_1
  - libsqlite=3.45.1=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_5
  - libsystemd0=255=h3516f8a_1
  - libtasn1=4.19.0=h166bdaf_0
  - libtiff=4.6.0=ha9c0a0a_2
  - libunistring=0.9.10=h7f98852_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.20.0=hd590300_0
  - libvorbis=1.3.7=h9c3ff4c_0
  - libvpx=1.13.1=h59595ed_0
  - libwebp-base=1.3.2=hd590300_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.6.0=hd429924_1
  - libxml2=2.12.5=h232c23b_0
  - libzlib=1.2.13=hd590300_5
  - llvm-openmp=15.0.7=h0cdce71_0
  - lz4-c=1.9.4=hcb278e6_0
  - markupsafe=2.1.5=py38h01eb140_0
  - matplotlib=3.3.4=py38h578d9bd_0
  - matplotlib-base=3.3.4=py38h0efea84_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=hfe3b2da_0
  - mpfr=4.2.1=h9458935_0
  - mpg123=1.32.4=h59595ed_0
  - mpmath=1.3.0=pyhd8ed1ab_0
  - mysql-common=8.0.33=hf1915f5_6
  - mysql-libs=8.0.33=hca2cd23_6
  - ncurses=6.4=h59595ed_2
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.1=pyhd8ed1ab_0
  - nspr=4.35=h27087fc_0
  - nss=3.98=h1d7d5a4_0
  - numpy=1.21.5=py38h1d589f8_1
  - ocl-icd=2.3.2=hd590300_0
  - ocl-icd-system=1.0.0=1
  - openh264=2.4.1=h59595ed_0
  - openjpeg=2.5.2=h488ebb8_0
  - openssl=3.2.1=hd590300_0
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=2.0.0=py38hdc8b05c_0
  - patsy=0.5.6=pyhd8ed1ab_0
  - pcre2=10.43=hcad00b1_0
  - pillow=10.2.0=py38ha43c96d_0
  - pip=24.0=pyhd8ed1ab_0
  - pixman=0.43.2=h59595ed_0
  - platformdirs=4.2.0=pyhd8ed1ab_0
  - ply=3.11=py_1
  - pooch=1.8.1=pyhd8ed1ab_0
  - portalocker=2.8.2=py38h578d9bd_1
  - pthread-stubs=0.4=h36c2ea0_1001
  - pugixml=1.14=h59595ed_0
  - pulseaudio-client=16.1=hb77b528_5
  - pyparsing=3.1.2=pyhd8ed1ab_0
  - pyqt=5.15.9=py38hffdaa6c_5
  - pyqt5-sip=12.12.2=py38h17151c0_5
  - pysocks=1.7.1=pyha2e5f31_6
  - python=3.8.18=hd12c33a_1_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.8=4_cp38
  - pytorch=2.1.0=py3.8_cuda11.8_cudnn8.7.0_0
  - pytorch-cuda=11.8=h7e8668a_5
  - pytorch-mutex=1.0=cuda
  - pytorch3d=0.7.5=py38_cu118_pyt210
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py38h01eb140_1
  - qt-main=5.15.8=h5810be5_19
  - readline=8.2=h8228510_1
  - requests=2.31.0=pyhd8ed1ab_0
  - scikit-learn=1.2.2=py38hd4b6e60_1
  - scipy=1.10.1=py38h10c12cc_0
  - seaborn=0.13.0=hd8ed1ab_0
  - seaborn-base=0.13.0=pyhd8ed1ab_0
  - setuptools=69.1.1=pyhd8ed1ab_0
  - sip=6.7.12=py38h17151c0_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.1.10=h9fff704_0
  - statsmodels=0.13.5=py38h26c90d9_2
  - svt-av1=1.8.0=h59595ed_0
  - sympy=1.12=pypyh9d50eac_103
  - tabulate=0.9.0=pyhd8ed1ab_1
  - tbb=2021.11.0=h00ab1b0_1
  - termcolor=2.4.0=pyhd8ed1ab_0
  - threadpoolctl=3.3.0=pyhc1e730c_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_0
  - tomli=2.0.1=pyhd8ed1ab_0
  - torchaudio=2.1.0=py38_cu118
  - torchtriton=2.1.0=py38
  - torchvision=0.16.0=py38_cu118
  - tornado=6.4=py38h01eb140_0
  - tqdm=4.66.2=pyhd8ed1ab_0
  - typing_extensions=4.10.0=pyha770c72_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xcb-util=0.4.0=hd590300_1
  - xcb-util-image=0.4.0=h8ee46fc_1
  - xcb-util-keysyms=0.4.0=h8ee46fc_1
  - xcb-util-renderutil=0.3.9=hd590300_1
  - xcb-util-wm=0.4.1=h8ee46fc_1
  - xkeyboard-config=2.41=hd590300_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libice=1.1.1=hd590300_0
  - xorg-libsm=1.2.4=h7391055_0
  - xorg-libx11=1.8.7=h8ee46fc_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h0b41bf4_1003
  - xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.6=h166bdaf_0
  - yacs=0.1.8=pyhd8ed1ab_0
  - yaml=0.2.5=h7f98852_2
  - zlib=1.2.13=hd590300_5
  - zstd=1.5.5=hfc55251_0
  - pip:
      - absl-py==2.1.0
      - addict==2.4.0
      - aiofiles==22.1.0
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.11
      - aiosignal==1.3.1
      - aiosqlite==0.20.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.3.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==2.4.1
      - async-timeout==5.0.1
      - attrs==23.2.0
      - autobahn==23.1.2
      - babel==2.14.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.1.0
      - blis==0.7.11
      - blobfile==2.1.1
      - cachetools==5.3.3
      - catalogue==1.0.2
      - cffi==1.16.0
      - chumpy==0.70
      - click==8.1.7
      - git+https://github.com/openai/CLIP.git
      - comm==0.2.1
      - cryptography==43.0.3
      - cymem==2.0.8
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - deprecation==2.1.0
      - distro==1.9.0
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.7.0
      - entrypoints==0.4
      - eval-type-backport==0.1.3
      - exceptiongroup==1.2.0
      - executing==2.0.1
      - fastjsonschema==2.19.1
      - fqdn==1.5.1
      - freetype-py==2.4.0
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - ftfy==6.1.3
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.28.1
      - google-auth-oauthlib==1.0.0
      - grpcio==1.62.0
      - h11==0.14.0
      - h5py==3.11.0
      - httpcore==1.0.4
      - httpx==0.27.0
      - hydra-core==1.3.2
      - hyperlink==21.0.0
      - imageio==2.34.0
      - importlib-metadata==7.0.2
      - importlib-resources==6.1.3
      - ipykernel==6.29.3
      - ipython==8.12.3
      - ipython-genutils==0.2.0
      - ipywidgets==8.1.2
      - isoduration==20.11.0
      - jedi==0.19.1
      - json5==0.9.22
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter==1.1.1
      - jupyter-client==7.4.9
      - jupyter-console==6.6.3
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-packaging==0.12.3
      - jupyter-server==2.13.0
      - jupyter-server-fileid==0.9.1
      - jupyter-server-proxy==4.4.0
      - jupyter-server-terminals==0.5.2
      - jupyter-server-ydoc==0.8.0
      - jupyter-ydoc==0.2.5
      - jupyterlab==3.6.7
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - jupyterlab-vpython==3.1.8
      - jupyterlab-widgets==3.0.10
      - lazy-loader==0.4
      - loralib==0.1.2
      - lxml==4.9.4
      - markdown==3.5.2
      - markdown-it-py==3.0.0
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - mesh2sdf==1.1.0
      - mistune==3.0.2
      - multidict==6.1.0
      - murmurhash==1.0.10
      - nbclassic==1.0.0
      - nbclient==0.9.0
      - nbconvert==7.16.2
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - notebook==6.5.6
      - notebook-shim==0.2.4
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open3d==0.13.0
      - openai==1.13.3
      - overrides==7.7.0
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pkgutil-resolve-name==1.3.10
      - plac==1.1.3
      - preshed==3.0.9
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - propcache==0.2.0
      - protobuf==4.25.3
      - psutil==5.9.8
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pycryptodomex==3.20.0
      - pydantic==2.6.3
      - pydantic-core==2.16.3
      - pyglet==2.0.14
      - pygments==2.17.2
      - pynavmesh==1.2.3
      - pyopengl==3.1.0
      - pyrender==0.1.45
      - python-json-logger==2.0.7
      - pywavelets==1.4.1
      - pyzmq==24.0.1
      - referencing==0.33.0
      - regex==2023.12.25
      - requests-oauthlib==1.3.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.7.1
      - rpds-py==0.18.0
      - rsa==4.9
      - rtree==1.2.0
      - scikit-image==0.21.0
      - send2trash==1.8.2
      - sentry-sdk==1.45.0
      - setproctitle==1.3.3
      - shapely==2.0.4
      - shtab==1.7.1
      - simpervisor==1.0.0
      - smmap==5.0.1
      - smplx==0.1.28
      - sniffio==1.3.1
      - soupsieve==2.5
      - spacy==2.3.4
      - srsly==1.0.7
      - stack-data==0.6.3
      - tensorboard==2.14.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - terminado==0.18.0
      - thinc==7.4.6
      - tifffile==2023.7.10
      - tinycss2==1.2.1
      - tomlkit==0.12.4
      - torch-dct==0.1.6
      - traitlets==5.14.1
      - trimesh==4.1.8
      - txaio==23.1.1
      - types-python-dateutil==2.8.19.20240106
      - tyro==0.8.3
      - uri-template==1.3.0
      - vpython==7.6.5
      - wandb==0.16.6
      - wasabi==0.10.1
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - werkzeug==3.0.1
      - widgetsnbextension==4.0.10
      - y-py==0.6.2
      - yarl==1.15.2
      - ypy-websocket==0.8.4
      - zipp==3.17.0
